// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BigStoreCore
{
    public partial class Category
    {
        public Category()
        {
            Product = new HashSet<Product>();
        }

        public int CategoryId { get; set; }
        public string Description { get; set; }
        public bool? IsRoot { get; set; }

        public virtual ICollection<Product> Product { get; set; }
    }
}